config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  post 'change', to:'carts#change' 
  get 'carts', to:'carts#remove_all'
  get 'place_order/:total', to:"order#place_order",as:'place_order'
  get 'orders', to: 'order#orders'
  post 'discount', to:"carts#discount"
  post 'customize_food', to: 'customizefoods#customize_food'
  get 'add_to_cart/:id' => 'carts#add_to_cart', :as => 'add_to_cart'
  get 'remove_from_the_cart/:id' =>'carts#remove_from_the_cart', :as => 'remove_from_the_cart'
  get 'carts/show'

  resources :carts
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_one :customizedfood
  belongs_to :discount,optional:true
  belongs_to :order,optional: true 
end

app/models/customizedfood.rb
class Customizedfood < ApplicationRecord
    belongs_to :item,optional: true
    belongs_to :cart,optional: true
    serialize :add_ons, Array
    ADD_ONS = %i[cheese tomato butter coriander]
end

app/models/discount.rb
class Discount < ApplicationRecord
    has_many :items
    has_many :carts
end

app/models/item.rb
class Item < ApplicationRecord
    has_one :customizedfood
    belongs_to :discount,optional:true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :order_session

  def change 
     @order = Order.find(session[:order_id])
     @item = Item.find(params[:item_id])
     @quantity = params[:quantity].to_i
     @cart_items = @order.carts.find_by(item_id: params[:item_id])
     @cart_items.quantity = @quantity
     @cart_items.subtotal = (@cart_items.unit_price)*@cart_items.quantity  
     @cart_items.save
     flash[:notice] = "Updated the cart"
     redirect_to carts_show_path
  end

  def show
    @order = Order.find(session[:order_id])
    @cart = @order.carts
  end

  def add_to_cart
    @order = Order.find(session[:order_id])
    @item = Item.find(params[:id])
    if @order.carts.find_by(item_id: @item.id).present?
      @cart_item =  @order.carts.find_by(item_id: params[:id])
      @cart_item.quantity = @cart_item.quantity + 1
    else
      @cart_item = Cart.create(:item_id => @item.id,
      :itemname => @item.itemname,
      :unit_price => @item.price,
      :subtotal => @item.price,
      :image => @item.image,
      :itemdescription => @item.itemdescription,
      :quantity => 1,
      :discount_id => @item.discount_id);
      if @item.customizedfood.present?
        @item.customizedfood.cart_id = @cart_item.id
        @item.customizedfood = nil
      end
      @order.carts << @cart_item
      flash[:notice] = "successfully added to the cart"
    end
    
    redirect_to carts_show_path
  end

  def discount
    @order = Order.find(session[:order_id])
    item = Item.find(params[:item_id])
    @cart_items = @order.carts.find_by(item_id: params[:item_id])
    @discount = (@cart_items.unit_price*@cart_items.discount.percentage)
    @cart_items.subtotal = (@cart_items.unit_price - @discount)*@cart_items.quantity  
    @cart_items.save 
    flash[:notice] = "Discount Applied"
    redirect_to carts_show_path
  end

  def destroy
    @cart_item = Cart.find(params[:id])
    @cart_item.destroy
    flash[:notice] = "successfully removed"
    redirect_to carts_show_path
  end

  private

  def order_session
    if session[:order_id]
      session[:order_id]
    else 
      @order=Order.create
      session[:order_id]=@order.id
    end 
  end 



end

app/controllers/customizefoods_controller.rb
class CustomizefoodsController < ApplicationController

    def customize_food
        @item = Item.find(params[:item_id])
        if @item.customizedfood.present?
            @item.customizedfood.add_ons = params[:add_ons]
            @item.customizedfood.description = params[:message]
            @item.customizedfood.save
        else 
            @customize_food = Customizedfood.create(
            :add_ons => params[:add_ons],
            :description => params[:message],
            :item_id => params[:item_id]
            )
        end
       redirect_to item_path(@item.id)
            
    end
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

 

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:itemname, :price,:itemdescription)
    end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController

    def orders 
        @orders = Order.all
    end
     
    def place_order
        @order = Order.find(session[:order_id])
        @order_items = @order.carts
        @order.total=params[:total].to_i
        @order.save
        flash[:notice] = "Successfully placed order"
        session[:order_id]=nil
        redirect_to items_path
    end

    private

  def order_session
    if session[:order_id]
      session[:order_id]
    else 
      @order=Order.create
      session[:order_id]=@order.id
    end 
  end 


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customizefoods_helper.rb
module CustomizefoodsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/_cart.html.erb
    <span><%=image_tag cart.image ,class:"img-thumbnail",style:"width:100px"%></span>
    <strong class="Cart_items">Itemname:</strong>
    <span class="cart_items_values"><%= cart.itemname %></span>|

    <strong class="Cart_items">Quantity:</strong>
    <span class="cart_items_values"><%= cart.quantity%></span>|

    <strong class="Cart_items">Price:</strong>
    <span class="cart_items_values"><%= cart.unit_price%></span>|

    <strong class="Cart_items">Subtotal:</strong>
    <span class="cart_items_values"><%= cart.subtotal%></span>|

    <strong class="Cart_items">Discount Available:</strong>
    <span class="cart_items_values"><%= @discount=cart.unit_price*cart.discount.percentage*cart.quantity%></span>|
     
  <%if cart.customizedfood.present?%>
     <span class="cart_items_values"><b>Add ons:</b><%= cart.customizedfood.add_ons.join(",")%></span>|
     <span class="cart_items_values"><b>Description:</b><%= cart.customizedfood.description%></span>|
  <% end %>

 
<div style="float:left;padding:20px 140px 0 0;">
  <%= form_with(url: change_path) do |f| %>
    <%= f.hidden_field :item_id,:value => cart.item_id  %>
    <%= f.hidden_field :subtotal,:value => cart.subtotal%>
    <button name="button" type="button" onclick="minus(this)">-</button>
    <%= f.number_field :quantity,min:0,max:100,value: cart.quantity,style:"width:40px"%>
    <button name="button" type="button" onclick="plus(this)">+</button>
    <%= submit_tag "Update cart",style:"margin-left:10px"%>
    <%= f.submit "Apply discount", formaction: discount_path%>
  <% end %>
    <span style="margin-left:400px"><%= button_to "remove item",cart_path(cart.id), method: :delete, class: "btn btn-primary"%>   </span>
  </div> 
  




<script>
    function plus(element){
      let quantity = element.previousElementSibling.value
      quantity++;
      element.previousElementSibling.value = quantity       
    }
    function minus(element){
        let quantity = element.nextElementSibling.value  
            if(quantity > 1){
            quantity--;
            element.nextElementSibling.value = quantity ;
            }
    }
</script>
<style>
  .Cart_items{
    padding-right:10px;
    padding-left:10px;
  }
  .cart_items_values{
    padding-right:10px;
  }

</style>

app/views/carts/show.html.erb
  <%if @cart.present?%>
     <%@total=0.0%>
      <% @cart.each do |cart| %>
        <div class="card">
          <div class="card-body" >
            <%= render cart %>
            <% @total = @total.to_d + cart.subtotal.to_d%>  
          </div>
         </div><br>
    <%end%>
   <p><strong>Total:</strong><%= @total %></p>
      <%=link_to "Place Order ",place_order_path(@total),class:"btn btn-primary"%><br>
<%else%>
 <h3 class="position-absolute top-50 start-50 translate-middle"> Cart is empty </h3>
<%end%>
<%if @cart.count == nil%>
 <%@items_in_the_cart = 0%>
<%else%>
  <%@items_in_the_cart = @cart.count%>
<%end%>

app/views/headers_footers/_header.html.erb
<nav class="navbar fixed-top navbar-expand-lg " style="background-color:#6495ED	">
  <div class="container-fluid" style="margin-left:100px">
     <%=link_to "Foodelicious",root_path,class:'nav-link btn'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%=link_to "Menu",items_path,class:'nav-link btn'%>
        </li>

        <li class="nav-item">
          <%=link_to "Cart(#{@items_in_the_cart})",carts_show_path,class:'nav-link btn'%>
        </li>

        <li class="nav-item">
          <%=link_to "Order",orders_path,class:'nav-link btn'%>
        </li>
      </ul>
      
    </div>
  </div>
</nav>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :itemname, style: "display: block" %>
    <%= form.text_field :itemname %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.number_field :rating %>
  </div>

  <div>
    <%= form.label :itemdescription, style: "display: block" %>
    <%= form.text_area :itemdescription %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <%=image_tag item.image,class:"img-fluid",style:"width:300px;height:200px" %>
  <p>
   <span > <%= item.itemname %></span><br>
   <span><%= item.itemdescription %></span><br>
    Price:<%= item.price %><br><br>
    <% if item.discount.present? %>
      Discount: <span><%= item.discount.name %></span><br>
    <%end%>
    <% if item.customizedfood.present? %>
      <% if item.customizedfood.description.present? %> 
        Description for the Chef :<span id="fooddescription"><%= item.customizedfood.description %></span><br>
      <% end %>
      <% if item.customizedfood.add_ons.present? %> 
        Add Ons :<span id="addons"><%= item.customizedfood.add_ons.join(",")%></span>
      <% end %>
    <% end %>
  </p>
  </p>
 </div>


 

app/views/items/index.html.erb
<div class="menu-container">
    <div class="row">
        <div class="col-12" >
           <div class="Search_box" style="margin-left:113px;position:fixed;width:103%;z-index:1">     
              <input  id="myInput" type="text" placeholder="search the item" style="width:80%;padding-left:20px" onkeyup= "search()">
           </div>
        </div>
    </div>
  <div class="container" style="padding:50px;">
  <div class="row row-cols-1 row-cols-md-3 g-3" id="card-container">
  <% @items.each do |item| %>
    <div class="col"  onclick="show(this)">
        <div class="card card-primary" style="overflow-y:scroll;overflow-y:hidden;height:300px;" onmouseover="this.style.opacity='0.5'" onmouseout="this.style.opacity='1'" >
          <div class="card-body" id="card-body">
            <%= render item %>
            <%= link_to "", item %>
          </div>
        </div>
      </div>
    <% end %>
    </div>
</div>


<div class="container text-center" id="search-results" >
        <h3>No items found.</h3>
</div>

<script>
   show = function (element) {
   let a = element.getElementsByTagName('a')[0].href
   window.location.href = a
   };

   function search() {
    var resultFound;
    const input=document.getElementById("myInput").value.toUpperCase();
    const cardContainer=document.getElementById("card-container");
    const cards= cardContainer.getElementsByClassName("card")
      for (i=0;i<cards.length;i++)

      {
          if(cards[i].getElementsByTagName('span')[0].innerHTML.toUpperCase().indexOf(input)>-1 || cards[i].getElementsByTagName('span')[1].innerHTML.toUpperCase().indexOf(input)>-1 ){
              cards[i].parentElement.style.display="";
               resultFound = true;
          }
          else{
              cards[i].parentElement.style.display="none";

          }
      }
        if(resultFound) {
        document.getElementById("search-results").style.display = "none";
    } else {
        document.getElementById("search-results").style.display = "";
    }
  }


</script>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<div  style="margin-left:100px;margin-right:100px">
  <div class="card-body">
    <%= render @item %>
    <div >
      <%=link_to "Add to Cart ",add_to_cart_path(@item.id), class:"btn btn-primary"%>
      <%= link_to "Back to items", items_path,class:"btn btn-primary" %>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" onclick="fun()" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Customize Food
      </button>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Customize Food</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with(url: customize_food_path) do |f| %>
            <%= f.hidden_field :item_id,:value => @item.id  %>
            <h5>Add ons:</h5> <br>
            <span id="checkbox"> <% Customizedfood::ADD_ONS.each do |key|%>
             <%= f.check_box :add_ons, {multiple: true}, key, nil%>
              <%= f.label key%>
            <%end%></span>

            <h5>Description for the chef</h5>
             <%= f.text_area :message, size: "50x5",id:"description" %>
           <span type="button" data-bs-toggle="modal" data-bs-target="#exampleModal1"> <%= f.submit "Add Customization"%></span>
        <%end%>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Success</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Added Customization to the item successfully
      </div>
    </div>
  </div>
</div>
<script>

  function fun(){
      let a = document.getElementById("fooddescription").innerHTML;
      let b = document.getElementById('checkbox').getElementsByTagName("input");
      let c = document.getElementById("addons").innerHTML;
      let d = c.split(",");
      for(let i in b)
      {
        for(let j in d)
        {  
          if(b[i].value == d[j])
            b[i].checked = true
        }
      }        
      let x = "";
      x += a;
      let y = document.getElementById("description");
      y.innerHTML = x;
  }

</script>
                     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zomato</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="hero_image" style= "background-color:#F8F8FF;margin-top:4rem;background-size:80rem,50rem;background-repeat: no-repeat;background-attachment: fixed;background-image:{ url(<%= asset_path 'sc-b1b92a3b316e19ad06d109e51884af71.jpg'%>),opacity:0.8}">
       
      <% flash.each do |type, msg| %>
       <div class="alert alert-info alert-dissmisible fade show">
         <%= msg %>
         <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" style="float:right"></button>
       </div>
      <% end %>

      
      <%= render 'headers_footers/header'%>
       <%= yield %>
  
  </body>
</html>

app/views/order/orders.html.erb
<%if @orders.present? %>
  <%@orders.each do |order|%>
  <% if order.total > 0%>
     <div class="card">
       <div class="card-header" style="background-color:">
          Order id: <%=order.id%>
       </div>
        <div class="card-body">
         <h5 class="card-title">
          <%order.carts.each do |ordered_items|%>
            <%= image_tag ordered_items.image,class:"img-thumbnail",style:"width:100px"%> 
              <%= ordered_items.itemname %> |
              <%if ordered_items.customizedfood.present?%>
                Add Ons: <%= ordered_items.customizedfood.add_ons.join(",")%>
                Description: <%= ordered_items.customizedfood.description%>
              <%end%> |
              Quantity:<%= ordered_items.quantity %>|
              Subtotal:<%= ordered_items.subtotal%><br><br>
          <%end%>
        </h5>
        <p class="card-text"><h5> Total price:<%=order.total%></h5>
      <%end %>
      </div>
    </div><br>
  <%end%>
<%else %>
  <h3>Place Order </h3>
<%end %>